export const productsList = [
    {
        id: 1,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1771921071420_Screenshot_2026-02-24_121739.png&w=1080&q=75",
        title: "Прыгуны",
        theme: "Приключения, Мультфильм, Комедия, Семейный",
        date: "05.03.2026",
        age: "6+",
        pre_sale: true,
        time: "01:50:00",
        top: 44,
        is_released: true,
        path: "priquni",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Дэниэл Чонг",
        actors: "Пайпер Курда, Бобби Мойнахан",
        description: "Учёные разработали технологию, позволяющую переносить человеческое сознание в максимально реалистичных роботизированных животных, что дает людям возможность общаться с животными. Мейбл, любительница животных, получает доступ к технологии. Она переносится в тело робота-бобра и отправляется исследовать животный мир.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "3/5/2026",
        movie_video: "https://www.youtube.com/embed/ngrz1qTFsq8?si=T7jqwazdbjcw6jTG",
        flags: [
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_(3-5).svg/1280px-Flag_of_the_United_Kingdom_(3-5).svg.png",
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png"
        ],
    },
    {
        id: 2,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1771921389861_Screenshot_2026-02-24_122303.png&w=1080&q=75",
        title: "Невеста!",
        theme: "Драма, Ужас, фантастика",
        date: "05.03.2026",
        age: "16+",
        pre_sale: true,
        time: "02:10:00",
        top: 44,
        year: 2024,
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        country: "Соединенные Штаты",
        director: "Мэгги Джилленхол",
        actors: "Джесси Бакли, Кристиан Бэйл",
        release_date: "3/5/2026",
        movie_video: "https://www.youtube.com/embed/qlpZFs9cthA?si=jcGJiZ8CQqWFvI0o",
        description: "Чикаго, 1930-е годы. Монстр Франкенштейна просит доктора Юфрониуса помочь создать ему компаньона. Вместе они оживляют убитую девушку, и она превосходит их ожидания.",
        is_released: false,
        path: "nevesta",
        flags: [
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png"
        ],
    },
    {
        id: 3,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1769677831531_Screenshot_2026-01-29_131020.png&w=1080&q=75",
        title: "Хамнет",
        date: "05.03.2026",
        age: "16+",
        pre_sale: true,
        top: 44,
        is_released: false,
        path: "hamnet",
        theme: "Приключения, Мультфильм, Комедия, Семейный",
        time: "02:10:00",
        year: 2024,
        country: "Соединенные Штаты",
        director: "Хлоя Чжао",
        actors: "Джеси Бакли, Пол Мескаль",
        description: "После смерти сына Гамнета Агнес остаётся в Стратфорде с детьми, а Уильям Шекспир возвращается в Лондон, чтобы написать пьесу, которая станет одним из его величайших творений.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "3/5/2026",
        movie_video: "https://www.youtube.com/embed/xYcgQMxQwmk?si=wpPC9ZbzjMBohCVe",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png"
        ],
    },
    {
        id: 4,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1771226282589_Screenshot_2026-02-16_111743.png&w=1080&q=75",
        title: "Наследник",
        date: "05.03.2026",
        age: "18+",
        pre_sale: true,
        top: 44,
        is_released: true,
        path: "naslednik",
        theme: "Драма, Комедия, Триллеры",
        time: "01:50:00",
        year: 0,
        country: "Соединенные Штаты",
        director: "Джон Паттон Форд",
        actors: "Глен Пауэлл, Маргарет Куолли, Эд Харрис, Тофер Грейс, Джессика Хенвик, Зак Вудс, Билл Кэмп",
        description: "Роскошные особняки, частные самолёты и даже собственные острова — состояние клана Редфеллоу исчисляется миллиардами. Всё это мечтает унаследовать Беккет, хоть глава рода и отрёкся от него ещё до его рождения. Однако на пути к заветной жизни стоят семь избалованных богачей. Чтобы ускорить свою очередь на наследство, Беккету придётся «спилить» несколько ветвей семейного древа. И сделать это так дерзко и изобретательно, чтобы избежать наказания за убийства.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "3/5/2026",
        movie_video: "https://www.youtube.com/embed/wotS3I1xImY?si=-Xzwf58zKwf4DfVJ",
        flags: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_the_United_Kingdom_(3-5).svg/1280px-Flag_of_the_United_Kingdom_(3-5).svg.png",
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png"
        ],
    },
    {
        id: 5,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1769673600868_Screenshot_2026-01-29_115949.png&w=1080&q=75",
        title: "Крик 7",
        date: "26.02.2026",
        age: "18+",
        pre_sale: true,
        top: 44,
        is_released: true,
        path: "krik",
        theme: "Ужас",
        time: "02:00:00",
        year: 0,
        country: "Соединенные Штаты",
        director: "Кевин Уильямсон",
        actors: "Нив Кэмпбелл, Кортни Кокс",
        description: "Когда в тихом городке, где Сидни Прескотт построила новую жизнь, появляется убийца Призрачное лицо, её самые тёмные страхи воплощаются в реальность: её дочь становится следующей целью. Стремясь защитить свою семью, Сидни должна столкнуться с ужасами прошлого, чтобы раз и навсегда положить конец кровопролитию.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "2/5/2026",
        movie_video: "https://www.youtube.com/embed/Ldw_ReVK8Ns?si=c9dDtELpR-f477wU",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png"
        ],
    },
    {
        id: 6,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1769494304982_Screenshot_2026-01-27_101137.png&w=1080&q=75",
        title: "GOAT: Мечтай по-крупному",
        date: "12.02.2026",
        age: "6+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "goat-mectay-po-krupnomu",
        theme: "Приключения, Мультфильм, Боевик, Семейный, Мюзикл",
        time: "01:40:00",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Тайри Диллихей, Адам Розетт",
        actors: "Калеб Маклафлин, Гэбриэл Юнион",
        description: "Когда в тихом городке, где Сидни Прескотт построила новую жизнь, появляется убийца Призрачное лицо, её самые тёмные страхи воплощаются в реальность: её дочь становится следующей целью. Стремясь защитить свою семью, Сидни должна столкнуться с ужасами прошлого, чтобы раз и навсегда положить конец кровопролитию.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "2/12/2026",
        movie_video: "https://www.youtube.com/embed/HPK4lRdptjc?si=K6kCNJ0kcOuPHka-",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
        ],
    },
    {
        id: 7,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1770145522199_Screenshot_2026-02-03_230500.png&w=1080&q=75",
        title: "Рай под ногами матерей 2: Письмо матери",
        date: "12.02.2026",
        age: "12+",
        pre_sale: false,
        top: 40,
        is_released: true,
        path: "ray-pod-noqami-materey-2-pismo-materi",
        theme: "Приключения, Драма",
        time: "01:40:00",
        year: 2025,
        country: "Соединенные Штаты",
        director: "Руслан Акун",
        actors: "Эмиль Эсеналиев, Павел Майков, Алексей Щербаков, Станислав Бондаренко, Омар Алибутаев",
        description: "Старые знакомые — Адиль, парень с доброй душой и интеллектом ребенка, и его девятилетний друг Самир, смышленый и смелый мальчишка — отправляются в полное испытаний путешествие из Кыргызстана через всю Россию в Москву, чтобы исполнить мечту мальчика.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "2/12/2026",
        movie_video: "https://www.youtube.com/embed/__pvwfjfiFM?si=dmLM9xv6wxnDTsrM",
        flags: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
        ],
    },
    {
        id: 8,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1769493884029_Screenshot_2026-01-27_100431.png&w=1080&q=75",
        title: "Грозовой перевал",
        date: "12.02.2026",
        age: "18+",
        pre_sale: false,
        top: 40,
        is_released: true,
        path: "qrozovoy-pereval",
        theme: "Приключения, Драма",
        time: "02:20:00",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Эмиральд Феннел",
        actors: "Джейкоб Элорди, Марго Робби",
        description: "По пути домой хозяин поместья «Грозовой перевал» мистер Эрншо подбирает на дороге одинокого сироту. Так Хитклифф обретает дом, семью и близкую подругу — с хозяйской дочерью Кэтрин они становятся неразлучны. После смерти мистера Эрншо дом наследует Хиндли, брат Кэтрин. Всю жизнь испытывая неприязнь и ревность к Хитклиффу, Хиндли оставляет парня в поместье лишь на правах прислуги. Единственное, что скрашивает его дни — время, проведённое с Кэтрин.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "2/12/2026",
        movie_video: "https://www.youtube.com/embed/tYtJ1Cu9zL4?si=Cw7KXli0JQwfJosX",
        flags: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
        ],
    },
    {
        id: 9,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1769672119787_Screenshot_2026-01-29_113503.png&w=1080&q=75",
        title: "Ограбление в Лос-Анджелесе",
        date: "12.02.2026",
        age: "16+",
        pre_sale: false,
        top: 40,
        is_released: true,
        path: "oqrableniye-v-los-andjeles",
        theme: "Драма, Триллеры, Криминал",
        time: "02:20:00",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Барт Лэйтон",
        actors: "Крис Хемсворт, Марк Руффало, Холли Берри, Барри Кеоган",
        description: "Дерзкие ограбления неуловимого вора Дэвиса вдоль знаменитого шоссе 101 поставили полицию в тупик. Планируя последнее дело, которое должно стать «ударом всей жизни», он сталкивается с разочаровавшимся страховым брокером Шэрон, переживающей собственный переломный момент. Неожиданное сотрудничество между ними привлекает внимание настойчивого детектива Лу, который стремится раскрыть дело любой ценой, повышая ставки до предела.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "2/12/2026",
        movie_video: "https://www.youtube.com/embed/Y0pE_4MaVVE?si=YY8k0rXO9MQXex5C",
        flags: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
        ],
    },
    {
        id: 10,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1766385580795_Screenshot_2025-12-22_102807.png&w=1080&q=75",
        title: "На помощь!",
        date: "12.02.2026",
        age: "18+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "na-pomosh",
        theme: "Ужас, Триллеры",
        time: "02:20:00",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Сэм Рэйми",
        actors: "Рэйчел Макадамс, Дилан О’Брайен",
        description: "Двое коллег оказываются на необитаемом острове, став единственными выжившими после авиакатастрофы. На острове им приходится забыть о прошлых обидах и работать сообща, чтобы выжить, но в конечном счёте им предстоит сразиться с самими собой, чтобы остаться в живых.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/29/2026",
        movie_video: "https://www.youtube.com/embed/mhCTh5lU2ds?si=khQ76csW-IVMJErH",
        flags: [
            "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
        ],
    },
    {
        id: 11,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1768579353517_Screenshot_2026-01-16_200222.png&w=1080&q=75",
        title: "Гренландия 2: Миграция",
        date: "12.02.2026",
        age: "16+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "grenlandiya-2-migraciya",
        theme: "Приключения, фантастика, Боевик, Триллеры",
        time: "01:50:00",
        year: 2025,
        country: "Соединенные Штаты",
        director: "Рик Роман Во",
        actors: "Морена Баккарин, Джерард Батлер",
        description: "Отголоски катастрофы, которая обрушилась на Землю пять лет назад, нависли над человечеством. Оставаться в Гренландии больше нельзя: тем немногим, кто сумел выжить, угрожает постоянный шквал осколков астероида. Человечество, а точнее то, что от него осталось, должно совершить самую важную и опасную миграцию в истории. Людям придется искать новое убежище.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/29/2026",
        movie_video: "https://www.youtube.com/embed/Tx42iCRm1WQ?si=uqeWCtPG1en4IwMv",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
        ],
    },
    {
        id: 12,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1758267691253_1080x_(16).jpeg.jpg&w=1080&q=75",
        title: "Аватар: Огонь и Пепел",
        date: "12.02.2026",
        age: "16+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "avatar-ogon-i-pepel",
        theme: "Приключения, фантастика, Боевик, Триллеры",
        time: "03:20:00",
        year: 2025,
        country: "Соединенные Штаты",
        director: "Джеймс Кэмерон",
        actors: "Кейт Уинслет, Зои Салдана, Стивен Лэнг, Сигурни Уивер",
        description: "Джейк Салли и Нейтири отправляются на другие планеты системы Альфа-Центавра.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "12/18/2025",
        movie_video: "",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 13,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1759736466373_Screenshot_2025-10-06_114055.png&w=1080&q=75",
        title: "Зверополис 2",
        date: "12.02.2026",
        age: "6+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "zveropolis-2",
        theme: "Приключения, фантастика, Боевик, Триллеры",
        time: "01:50:00",
        year: 2025,
        country: "Соединенные Штаты",
        director: "Джаред Буш, Байрон Ховард",
        actors: "Джейсон Бейтман, Иветт Николь Браун",
        description: "Кролик-полицейский Джуди и лис Ник идут по следу загадочной рептилии, чьё прибытие в Зверополис переворачивает жизнь города с ног на голову. Чтобы раскрыть дело, Джуди и Ник вынуждены работать под прикрытием в разных районах города.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "11/27/2025",
        movie_video: "https://www.youtube.com/embed/OmJVDHPKoH0?si=juh1yGSht_XtNJM0",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 14,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1743592131400_POSTER.jpg&w=1080&q=75",
        title: "Апатия 2",
        date: "12.02.2026",
        age: "18+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "apatiya-2",
        theme: "Триллеры",
        time: "01:10:00",
        year: 2025,
        country: "Азербайджан",
        director: "Хикмет Рагимов",
        actors: "Турал Бахыш Шахла Алигызы Фуад Джабиев",
        description: "Главный герой фильма, Акиф, убегает из детского дома, чтобы найти свою мать. На этом мучительном пути, конец которого кажется туманным, герой сталкивается с множеством трудностей. Быстрая реакция сотрудника прокуратуры на происходящее поднимает перед зрителем множество вопросов о сути жизни. «Апатия-2» с силой даёт пощёчину менталитету, который бездумно приводит детей в этот мир.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/15/2026",
        movie_video: "https://www.youtube.com/embed/IjN1DmY4Vwg?si=vFzXF05GDBL82yUA",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 15,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1765787960303_Screenshot_2025-12-15_123912.png&w=1080&q=75",
        title: "Буратино",
        date: "12.02.2026",
        age: "6+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "buratino",
        theme: "Семейный",
        time: "01:50:00",
        year: 2025,
        country: "Россия",
        director: "Игорь Волошин",
        actors: "Виталия Корниенко, Александр Петров, Рузиль Минекаев",
        description: "Однажды к папе Карло попадает древний волшебный ключ, который помогает исполнить любое желание. Одинокий мастер хочет только одного — сына. Желание уже почти исполнилось, но полено оживает, из него появляется умный, веселый и деревянный мальчик. Папа Карло очень любит сына, но Буратино постепенно понимает, что он не такой, как все, и отправляется в длинное и полное приключений путешествие, чтобы доказать папе: он хороший и настоящий сын.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/1/2026",
        movie_video: "https://www.youtube.com/embed/9XNkWa8pYto?si=ZQzAAf4QEoihYipv",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 16,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1765869461209_Screenshot_2025-12-16_111707.png&w=1080&q=75",
        title: "Три богатыря и свет клином",
        date: "12.02.2026",
        age: "6+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "tri-boqatirya-i-svet-klinom",
        theme: "Приключения, Мультфильм",
        time: "01:50:00",
        year: 2025,
        country: "Россия",
        director: "Дарина Шмидт",
        actors: "Сергей Маковецкий, Юлия Зоркина, Дмитрий Высоцкий",
        description: "Богатыри ждут пополнения в своих семействах, но отечество снова нужно спасать. Нагрянула огромная, невесть откуда взявшаяся, туча и грозит затмить весь белый свет и превратить день в ночь. Оставив все дела семейные, богатыри бросаются навстречу опасности. А хитрый купец Колыван как будто этого и ждал: набрав себе в помощники злодеев из подручных Бабы Яги, напал на княжество и много дел плохих натворил. Но не все коту масленица. Богатыри идут на помощь Князю, городу и верному Коню Юлию.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/8/2026",
        movie_video: "https://www.youtube.com/embed/yiU5T1ng7hI?si=WVB_ZgA_2rCJLX54",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 17,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1766041486437_Screenshot_2025-12-18_110436.png&w=1080&q=75",
        title: "Казнить нельзя помиловать",
        date: "12.02.2026",
        age: "18+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "kaznit-nelzya-pomilovat",
        theme: "Драма, Боевик, Триллеры, Криминал",
        time: "01:50:00",
        year: 2025,
        country: "Соединенные Штаты",
        director: "Тимур Бекмамбетов",
        actors: "Ребекка Фергюсон, Крис Пратт",
        description: "Ближайшее будущее, Лос-Анджелес. Детектив полиции Крис Рейвен задержан по обвинению в убийстве своей жены. В течение 90 минут Крис должен доказать свою невиновность продвинутому искусственному интеллекту, который выступает в роли судьи и палача.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/22/2026",
        movie_video: "https://www.youtube.com/embed/O5Pr32yHDIE?si=uRj5_eoj_RFuHZJo",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 18,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1766385580795_Screenshot_2025-12-22_102807.png&w=1080&q=75",
        title: "На помощь!",
        date: "12.02.2026",
        age: "18+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "na-pomosh",
        theme: "Драма, Боевик, Триллеры, Криминал",
        time: "02:00:00",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Сэм Рэйми",
        actors: "Рэйчел Макадамс, Дилан О’Брайен",
        description: "Двое коллег оказываются на необитаемом острове, став единственными выжившими после авиакатастрофы. На острове им приходится забыть о прошлых обидах и работать сообща, чтобы выжить, но в конечном счёте им предстоит сразиться с самими собой, чтобы остаться в живых.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/29/2026",
        movie_video: "https://www.youtube.com/embed/mhCTh5lU2ds?si=9dushhfZJpMDFbGG",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 19,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1766574839639_111225-01_RETURN_TO_SILENT_HILL_poster_10801350.jpg&w=1080&q=75",
        title: "Возвращение в Сайлент Хилл",
        date: "12.02.2026",
        age: "18+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "vozvrasheniye-v-saylent-xill",
        theme: "Ужас",
        time: "01:50:00",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Кристоф Ган",
        actors: "Джереми Ирвин, Ханна Эмили Андерсон",
        description: "Джеймс Сандерленд тяжело переживает разлуку со своей возлюбленной и получает таинственное письмо, которое приводит его в город Сайлент Хилл. Джеймс надеется найти её там, однако город сильно изменился под влиянием некой зловещей силы. Джеймс исследует Сайлент Хилл и сталкивается с пугающими существами и образами — как знакомыми, так и незнакомыми. Сомневаясь в своём рассудке, он пытается отличить реальность от иллюзий и сохранить достаточно сил, чтобы спасти свою возлюбленную.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/22/2026",
        movie_video: "https://www.youtube.com/embed/hXqbi4q3NGs?si=0YgSYQ3PCZY3YIDy",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 20,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1768579353517_Screenshot_2026-01-16_200222.png&w=1080&q=75",
        title: "Гренландия 2: Миграция",
        date: "12.02.2026",
        age: "16+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "qrenlandiya-2-miqraciya",
        theme: "Приключения, фантастика, Боевик, Триллеры",
        time: "01:50:00",
        year: 2025,
        country: "Соединенные Штаты",
        director: "Рик Роман Во",
        actors: "Морена Баккарин, Джерард Батлер",
        description: "Отголоски катастрофы, которая обрушилась на Землю пять лет назад, нависли над человечеством. Оставаться в Гренландии больше нельзя: тем немногим, кто сумел выжить, угрожает постоянный шквал осколков астероида. Человечество, а точнее то, что от него осталось, должно совершить самую важную и опасную миграцию в истории. Людям придется искать новое убежище.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/29/2026",
        movie_video: "https://www.youtube.com/embed/Tx42iCRm1WQ?si=2FpQE1m17xLMIQjy",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 21,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1768579732013_Screenshot_2026-01-16_200842.png&w=1080&q=75",
        title: "Марти Великолепный",
        date: "12.02.2026",
        age: "18+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "marti-velikolepniy",
        theme: "Комедия",
        time: "02:30:00",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Джош Сэфди",
        actors: "Тимоти Шаламе , Гвинет Пэлтроу",
        description: "Молодой амбициозный парень Марти Маузер готов пойти на всё ради осуществления своей мечты, чтобы доказать всему миру, что для него нет ничего невозможного.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/29/2026",
        movie_video: "https://www.youtube.com/embed/rdw3xjMVxPI?si=h4VUR8ss2485IZW7",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 22,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1768580145906_Screenshot_2026-01-16_201531.png&w=1080&q=75",
        title: "Чарли Чудо-пёс",
        date: "12.02.2026",
        age: "6+",
        pre_sale: false,
        top: 44,
        is_released: true,
        path: "charli-chudo-pyos",
        theme: "Мультфильм, фантастика, Комедия",
        time: "01:40:00",
        year: 2026,
        country: "Канада",
        director: "Ши Уэйгман",
        actors: "Оуэн Уилсон , Табита Сен-Жермен",
        description: "Девятилетний Дэнни и его пёс Чарли, получивший суперспособности после похищения инопланетянами, пытаются помешать соседскому коту Пудингу осуществить злодейский план по захвату мира.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "1/29/2026",
        movie_video: "https://www.youtube.com/embed/UfVhCLD9QRM?si=s0sV0vhHVoft0dlq",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
    {
        id: 23,
        image: "https://new.parkcinema.az/_next/image?url=https%3A%2F%2Fnew.parkcinema.az%2Fapi%2Ffile%2FgetFile%2F1773220662973_Screenshot_2026-03-11_131736.png&w=1080&q=75",
        title: "Я иду искать 2",
        date: "12.02.2026",
        age: "18+",
        pre_sale: true,
        top: 44,
        is_released: false,
        path: "ready-or-not-2-here-i-come",
        theme: "Ужас, Комедия, Триллеры",
        time: "01:44:00",
        year: 2026,
        country: "Соединенные Штаты",
        director: "Мэттью Беттинелли, Тайлер Джиллетт",
        actors: "Самара Уивинг, Кэтрин Ньютон",
        description: "Пережив нападение со стороны проклятой семьи мужа, Грейс попадает на новый уровень опасной игры. Грейс узнаёт, что теперь опасность грозит её младшей сестре Фейт. Вместе сёстры противостоят четырём могущественным семьям, которые пытаются убить их, чтобы сохранить свои власть и богатства.",
        subtitleLanguage: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/1280px-Flag_of_Azerbaijan.svg.png",
        release_date: "3/26/2026",
        movie_video: "https://www.youtube.com/embed/COOgecZBfe8?si=ovpzkeXLbqbuqT4D",
        flags: [
            "https://upload.wikimedia.org/wikipedia/en/thumb/f/f3/Flag_of_Russia.svg/330px-Flag_of_Russia.svg.png",
            "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg",
            "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_the_United_Kingdom_%283-5%29.svg"
        ],
    },
]